#!/usr/bin/env python3
from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.sources import SOURCES  # noqa: E402


TARGET = ROOT / "docs" / "SOURCES.md"


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def render() -> str:
    kinds = Counter(source.kind for source in SOURCES)
    sites = Counter(source.site for source in SOURCES)
    lines = [
        "# Source catalog",
        "",
        "<!-- Generated by scripts/generate-source-catalog.py; do not edit manually. -->",
        "",
        f"Configured sources: **{len(SOURCES)}** "
        f"({kinds.get('scrape', 0)} scrape + {kinds.get('pipeline', 0)} pipeline).",
        "",
        "Sites: " + ", ".join(f"`{site}` ({count})" for site, count in sorted(sites.items())) + ".",
        "",
        "| Source ID | Site | Category | Kind | Stale hours | Description |",
        "| --- | --- | --- | --- | ---: | --- |",
    ]
    for source in sorted(SOURCES, key=lambda item: (item.site, item.category, item.id)):
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{_cell(source.id)}`",
                    _cell(source.site),
                    _cell(source.category),
                    _cell(source.kind),
                    _cell(source.stale_hours if source.stale_hours is not None else "global"),
                    _cell(source.description),
                ]
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "Every source is available at `GET /datasets/{source_id}` after its first successful refresh.",
            "Pipeline sources are refreshed by dedicated commands/timers and are excluded from the generic scrape planner.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
            print(f"{TARGET.relative_to(ROOT)} is out of date; run {Path(__file__).name}")
            return 1
        return 0
    TARGET.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
